### ISSUE TITLE
Update Map Pool To Reflect Overwatch 2 Competitive Map Pool

### ISSUE THREAD

**Issue by ryansbuendorf** [steven11sjf/gopherwatch-league-site#21]
Overwatch 2 has removed the Assault game mode so maps such as...
- Paris
- Horizon Lunar Colony
- Hanamura
- Volskaya Industries
- Temple of Anubis
Can no longer be played. We also need to add the new Push game mode maps to the pool

**Comment by steven11sjf** [comment]
Maps are written in the spreadsheet, I can update the dropdowns. The names are converted to links in /public/js/schedule-page.js in getMapImage(). I am already working on adding this.
