### ISSUE TITLE
Wags shows his name as "È‚ssquatch#1406" rather than "Ȃssquatch#1406" in stats

### ISSUE THREAD

**Issue by steven11sjf** [steven11sjf/gopherwatch-league-site#7]
![image](https://user-images.githubusercontent.com/25016775/161121008-cccae866-55f7-484a-b101-3de532cac85a.png)

breaks team page and player page links as well. could be an issue with Boonie's stats program messing up character encodings.

**Comment by steven11sjf** [comment]
Seems to be an issue with Google's character encoding vs what Boonie uses. I assume I can figure out what encoding google is and have him update it in stats but this is easily fixed by find+replace every time stats are updated, so I will look into it later.

**Comment by ryansbuendorf** [comment]
Wags will not be playing this season. We can reopen another issue if we run into another troublesome battle tag in the future.
